---
title: "NY Weather Dashboard"
output:  
  flexdashboard::flex_dashboard:
    theme: yeti
    orientation: columns
    vertical_layout: fill
---

```{r, include=FALSE}
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
data("ny_noaa")


ny_noaa = 
  ny_noaa %>%
  sample_n(5000) %>%
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>%
  mutate(
    tmax = as.numeric(tmax),
    tmin = as.numeric(tmin),
    snow_mm = snow,
    snow = round(snow_mm * 0.03937 * 4) / 4)

```

 
Column {data-width=650}
-----------------------------------------------------------------------

### Snowfall by year

```{r}
  ny_noaa %>% 
  mutate(text_label = str_c("Snow (mm)")) %>% 
  plot_ly(
    x = ~year, y = ~snow, color = ~snow, type = "bar", colors = "viridis", 
    text = ~text_label, alpha = 0.4)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Temperature trends by month

```{r}
 ny_noaa %>% 
    mutate(text_label = str_c("month", month)) %>% 
  plot_ly(x = ~tmin, y = ~tmax, color = ~month, type = "scatter", mode = "markers", alpha = 0.5, text = ~text_label)
```

### Distribution of temperatures in January

```{r, echo=FALSE}
  ny_noaa %>% 
<<<<<<< HEAD
  mutate(day = as.factor(day),
         day = fct_reorder(day, tmin)) %>% 
  filter(month == 1) %>%
  plot_ly(
     y = ~tmin, color = ~day, type = "box", colors = "viridis")


nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
=======
  mutate(text_label = str_c("day")) %>% 
  filter(month == 1) %>%
  plot_ly(x= ~day,
     y = ~tmin, type = "box", color = ~day)
>>>>>>> b30203818e346814e799913d459660622dc89502

```
```
